[server]
runOnSave = true
enableStaticServing = true

[[theme.fontFaces]]
family = "Quicksand"
url = "assets/Quicksand-Regular.ttf"
style = "normal"
weight = 400

[[theme.fontFaces]]
family = "Quicksand"
url = "assets/Quicksand-Medium.ttf"
style = "normal"
weight = 500

[[theme.fontFaces]]
family = "Quicksand"
url = "assets/Quicksand-SemiBold.ttf"
style = "normal"
weight = 600

[[theme.fontFaces]]
family = "Quicksand"
url = "assets/Quicksand-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "Quicksand"
url = "assets/Quicksand-Light.ttf"
style = "normal"
weight = 300

[theme]
font = "Quicksand"
base = "light"